### ISSUE TITLE
redundant conformance to CKRecordRepresentable error

### ISSUE THREAD

**Issue by MadeByDouglas** [ggirotto/NestedCloudKitCodable#2]
Not sure if I am missing something, however in the `CKRecordRepresentable.swift` when you use a `typealias` for `CKEncodable` `CKDecoable` and `CKCodable` it causes an error.

I fixed this by changing them all to protocols rather than type alias, which is how it was in the `CustomCloudKitEncodable` project.

**Comment by ggirotto** [comment]
Hi @MadeByDouglas, thanks for the report. Sorry about the delay. Can you provide a little bit more information? What error have you faced?

**Comment by MadeByDouglas** [comment]
the error is when you try to use a struct and have it adhere to the CKCodable protocol. it says "redundant conformance to protocol CKRecordRepresentable"

<img width="681" alt="Screen Shot 2019-07-23 at 10 26 50 PM" src="https://user-images.githubusercontent.com/10858053/61762917-27bfe600-ad99-11e9-8170-700b806d67be.png">
<img width="960" alt="Screen Shot 2019-07-23 at 10 26 41 PM" src="https://user-images.githubusercontent.com/10858053/61762918-28587c80-ad99-11e9-9f5f-9c4701b04ccd.png">

**Comment by ggirotto** [comment]
I'm afraid is not just the struct the problem you are facing. If you look at the [Example Objects](https://github.com/ggirotto/NestedCloudKitCodable/tree/master/NestedCKCodableExamples/Example%20Objects) of the project you'll see that all of them are structs as well. May you provide me an example project reproducing the bug?

**Comment by MadeByDouglas** [comment]
Right, its not just because of structs. I’m not sure why it works in the example project and not mine. Sorry don’t have time to troubleshoot any further at the moment since I found a work around.
