### ISSUE TITLE
NestedCloudKitCodable.CKCodableError.ErrorType.recordNotFound

### ISSUE THREAD

**Issue by HasanKassem** [ggirotto/NestedCloudKitCodable#3]
Hello,
I'm having a problem retrieving the data. I have two main classes, where one have an array of the other. When this array is empty, all the data are saved and retrieved correctly. But when the array is not empty, I get the following error:
`NestedCloudKitCodable.CKCodableError.ErrorType.recordNotFound`

I'm not sure what may be the cause of this problem. Any help is appreciated.

**Comment by HasanKassem** [comment]
Yes I just encoded my objects as data.. But it would be nice if this problem can be fixed

**Comment by ggirotto** [comment]
Hi @HasanKassem I've recently released a new version (1.0.3), could you please update and see if the error persists?

If you could provide the class structures, it would help me a lot in fixing this issue.

**Comment by HasanKassem** [comment]
It's working now, thank you. But I'm having another issue, when trying different zone using `CKRecordEncoder(zoneID: )` I'm getting **ZoneId provided doesn't match target zone**.

**Comment by HasanKassem** [comment]
Okay so the problem was in
`private func produceReference(for value: CKEncodable) throws -> CKRecord.Reference {
        let recordID = CKRecord.ID(recordName: value.cloudKitIdentifier)
        return CKRecord.Reference(recordID: recordID, action: .deleteSelf)
    }`
I changed it to
`private func produceReference(for value: CKEncodable) throws -> CKRecord.Reference {
        let recordID = CKRecord.ID(recordName: value.cloudKitIdentifier, zoneID: zoneID ?? .default)
        return CKRecord.Reference(recordID: recordID, action: .deleteSelf)
    }`

**Comment by ggirotto** [comment]
Thanks for the PR!

**Comment by ggirotto** [comment]
@HasanKassem I published 1.0.4 which includes yours fix. Thanks again.
